### ISSUE TITLE
unexpected '{' Error

### ISSUE THREAD

**Issue by wenching33** [ipeter50/ken-burns-effect#3]
Even if I modified the path of helper_math.h, I got the following error.
Can you help me with the " unexpected '{' in field name" ERROR ?
What does that means ?

Traceback (most recent call last):
  File "kbe.py", line 181, in <module>
    ken_burn_pipe((tensorImage+1)/2, zoom_settings, output_path, pretrained_estim=pretrained_estim)
  File "/home/liaowq2/code/ken-burns-effect/utils/pipeline.py", line 118, in __call__
    }, self.objectCommon, self.moduleInpaint)
  File "/home/liaowq2/code/ken-burns-effect/utils/common.py", line 213, in process_kenburns
    objectCommon['dblBaseline'])
  File "/home/liaowq2/code/ken-burns-effect/utils/common.py", line 515, in render_pointcloud
    'zee': tensorZee
  File "/home/liaowq2/code/ken-burns-effect/utils/common.py", line 295, in preprocess_kernel
    '''.format(path_to_math_helper) + strKernel
ValueError: unexpected '{' in field name

**Comment by pierlj** [comment]
This was due to bad formating inside the kernel preparation script. That should be fixed now. 

I can't test it properly right now, but let me see if you have any trouble to make it work.

**Comment by wenching33** [comment]
Thanks for your reply.
I fixed this by substitute '{' by '{{' and '}' by '}}' in utils/common.py: 271
![image](https://user-images.githubusercontent.com/38348587/127981951-a593feae-35b3-499c-9b68-69ed11ea6bbf.png)
