### ISSUE TITLE
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

### ISSUE THREAD

**Issue by DAVID-Hown** [ipeter50/ken-burns-effect#8]
[
![image](https://user-images.githubusercontent.com/55193099/157794009-c2371c42-8c3d-44b8-8b12-182b3f173332.png)
](url)

**Comment by DAVID-Hown** [comment]
Number of threads used:  24
Loading models parameters...
./models/trained/disparity-estimation-no-mask.tar
Model disparity loaded succesfully.
./models/trained/disparity-refinement.tar
Model refine loaded succesfully.
./models/trained/inpainting-color.tar
Model inpaint loaded succesfully.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 685, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 139, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 151, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 67, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kbe.py", line 182, in <module>
    ken_burn_pipe((tensorImage+1)/2, zoom_settings, output_path, pretrained_estim=pretrained_estim)
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/pipeline.py", line 118, in __call__
    }, self.objectCommon, self.moduleInpaint)
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 213, in process_kenburns
    objectCommon['dblBaseline'])
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 516, in render_pointcloud
    'zee': tensorZee
  File "cupy/_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 380, in launch_kernel
    return cupy.cuda.compile_with_cache(strKernel, tuple([ '-I ' + os.environ['CUDA_HOME'], '-I ' + os.environ['CUDA_HOME'] + '/include' ])).get_function(strFunction)
  File "/opt/conda/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 464, in compile_with_cache
    return _compile_module_with_cache(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 495, in _compile_module_with_cache
    cache_in_memory, jitify)
  File "/opt/conda/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 572, in _compile_with_cache_cuda
    log_stream, cache_in_memory, jitify)
  File "/opt/conda/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 322, in compile_using_nvrtc
    name_expressions, log_stream, jitify)
  File "/opt/conda/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 305, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/opt/conda/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 703, in compile
    'nvrtc' if not runtime.is_hip else 'hiprtc')
cupy.cuda.compiler.CompileException: /tmp/tmpl2nqs1wc/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu(2): catastrophic error: cannot open source file "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h"

1 catastrophic error detected in the compilation of "/tmp/tmpl2nqs1wc/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu".
Compilation terminated.

**Comment by DAVID-Hown** [comment]
can you help me ?
my env:
OS                           : Linux-4.9.0-8-amd64-x86_64-with-glibc2.27
Python Version               : 3.9.2
CuPy Version                 : 10.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.1
SciPy Version                : 1.6.1
Cython Build Version         : 0.29.24
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 10020
CUDA Driver Version          : 10020
CUDA Runtime Version         : 10020
cuBLAS Version               : 10203
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (10, 3, 0)
cuSPARSE Version             : 10301
NVRTC Version                : (10, 2)
Thrust Version               : 100907
CUB Build Version            : 100800
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8300
cuDNN Version                : 8101
NCCL Build Version           : 21104
NCCL Runtime Version         : 2804
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:18:00.0
Device 1 Name                : Tesla V100-SXM2-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:3B:00.0
Device 2 Name                : Tesla V100-SXM2-32GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:AF:00.0

**Comment by pierlj** [comment]
This is probably because you have to change this path "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h" to the actual path in your machine, check issue #2.
